[package]
name = "ft"
version = "0.1.0"
edition = "2021"

[features]
profile = ["mini/profile"]

[dependencies]
blake3 = "1.5.4"
crc32fast = "1.4.2"
mini = { git = "http://github.com/zx3no/mini", version = "0.1.0", features = ["profile"] }
walkdir = "2.5.0"
